Update fiadel

diff --git a/fiadel b/fiadel
--- a/fiadel
+++ b/fiadel
@@ -1,37 +1,253 @@
 #!/bin/bash
 
-# Ensure you are running as root
-if [ "$(id -u)" -ne 0 ]; then
-    echo "You need to run this script as root."
+if [[ $EUID -ne 0 ]]; then
+    clear
+    echo "You should run this script with root!"
+    echo "Use sudo -i to change user to root"
     exit 1
 fi
 
-# Stop Fail2Ban service
-echo "Stopping Fail2Ban..."
-systemctl stop fail2ban
+function main_menu {
+    clear
+    echo "----------- IR-ISP-Blocker -----------"
+    echo "https://github.com/Kiya6955/IR-ISP-Blocker"
+    echo "--------------------------------------"
+    echo "Which ISP do you want to perform an action on?"
+    echo "--------------------------------------"
+    echo "1-Hamrah Aval"
+    echo "2-Irancell"
+    echo "3-Mokhaberat"
+    echo "4-Rightel"
+    echo "5-Shatel"
+    echo "6-AsiaTech"
+    echo "7-Pishgaman"
+    echo "8-MobinNet"
+    echo "9-ParsOnline"
+    echo "10-Hetzner"
+    echo "11-Unblock All"
+    echo "12-Exit"
+    read -p "Enter your choice: " isp
+    case $isp in
+    1) isp="MCI" blocking_menu ;;
+    2) isp="MTN" blocking_menu ;;
+    3) isp="TCI" blocking_menu ;;
+    4) isp="Rightel" blocking_menu ;;
+    5) isp="Shatel" blocking_menu ;;
+    6) isp="AsiaTech" blocking_menu ;;
+    7) isp="Pishgaman" blocking_menu ;;
+    8) isp="MobinNet" blocking_menu ;;
+    9) isp="ParsOnline" blocking_menu ;;
+    10) isp="Hetzner" blocking_menu ;;
+    11) unblocker ;;
+    12) echo "Exiting..."; exit 0 ;;
+    *) echo "Invalid option"; main_menu ;;
+    esac
+}
 
-# Delete all Fail2Ban jails
-echo "Deleting all Fail2Ban jails..."
-fail2ban-client stop all
+function blocking_menu {
+    echo "ٌWait a minute, installing prerequisites..."
+    sleep 2s
 
-# Restart Fail2Ban to apply changes
-echo "Restarting Fail2Ban..."
-systemctl restart fail2ban
+    clear
 
-# Flush all iptables rules
-echo "Flushing all iptables rules..."
-iptables -F
+    if ! dpkg -l | grep -q iptables; then
+        apt update
+        apt install -y iptables
+    fi
 
-# Delete all user-defined iptables chains
-echo "Deleting all user-defined iptables chains..."
-iptables -X
+    if ! dpkg -l | grep -q iptables-persistent; then
+        apt update
+        apt install -y iptables-persistent
+    fi
 
-# Remove Fail2Ban
-echo "Uninstalling Fail2Ban..."
-apt-get remove --purge -y fail2ban
+    if ! iptables -L isp-blocker -n >/dev/null 2>&1; then
+        iptables -N isp-blocker
+    fi
 
-# Remove iptables if needed (optional)
-# echo "Uninstalling iptables..."
-# apt-get remove --purge -y iptables
+    if ! iptables -C INPUT -j isp-blocker &> /dev/null; then
+        iptables -I INPUT -j isp-blocker
+    fi
 
-echo "All Fail2Ban and iptables rules have been deleted."
+    clear
+
+    case $isp in
+        "MCI")
+            IP_LIST=$(curl -s 'https://raw.githubusercontent.com/Kiya6955/IR-ISP-Blocker/main/mci-ips.ipv4')
+            ;;
+        "MTN")
+            IP_LIST=$(curl -s 'https://raw.githubusercontent.com/Kiya6955/IR-ISP-Blocker/main/mtn-ips.ipv4')
+            ;;
+        "TCI")
+            IP_LIST=$(curl -s 'https://raw.githubusercontent.com/Kiya6955/IR-ISP-Blocker/main/tci-ips.ipv4')
+            ;;
+        "Rightel")
+            IP_LIST=$(curl -s 'https://raw.githubusercontent.com/Kiya6955/IR-ISP-Blocker/main/rightel-ips.ipv4')
+            ;;
+        "Shatel")
+            IP_LIST=$(curl -s 'https://raw.githubusercontent.com/Kiya6955/IR-ISP-Blocker/main/shatel-ips.ipv4')
+            ;;
+        "AsiaTech")
+            IP_LIST=$(curl -s 'https://raw.githubusercontent.com/Kiya6955/IR-ISP-Blocker/main/asiatech-ips.ipv4')
+            ;;
+        "Pishgaman")
+            IP_LIST=$(curl -s 'https://raw.githubusercontent.com/Kiya6955/IR-ISP-Blocker/main/pishgaman-ips.ipv4')
+            ;;
+        "MobinNet")
+            IP_LIST=$(curl -s 'https://raw.githubusercontent.com/Kiya6955/IR-ISP-Blocker/main/mobinnet-ips.ipv4')
+            ;;
+        "ParsOnline")
+            IP_LIST=$(curl -s 'https://raw.githubusercontent.com/Kiya6955/IR-ISP-Blocker/main/parsan-ips.ipv4')
+            ;;
+        "Hetzner")
+            IP_LIST=$(curl -s 'https://raw.githubusercontent.com/Kiya6955/IR-ISP-Blocker/main/hetzner-ips.ipv4')
+            ;;
+    esac
+
+    if [ $? -ne 0 ]; then
+        echo "Failed to fetch the IP list. Please contact @Kiya6955"
+        read -p "Press enter to return to Menu" dummy
+        blocking_menu
+    fi
+
+    clear
+
+    echo "---------- $isp Menu ----------"
+    echo "1-Block $isp"
+    echo "2-$isp Only"
+    echo "3-Back to Main Menu"
+    read -p "Enter your choice: " choice
+    case $choice in
+        1) blocker ;;
+        2) only_mode ;;
+        3) main_menu ;;
+        *) echo "Invalid option press enter"; blocking_menu ;;
+    esac
+}
+
+function blocker {
+    clear
+    echo "Choose an option:"
+    echo "1-Block specific ports for $isp"
+    echo "2-Block all ports for $isp"
+    echo "3-Back to Main Menu"
+    read -p "Enter your choice: " choice
+
+    clear
+    read -p "Enter IP addresses you want whitelist for $isp (separate with comma like 1.1.1.1,8.8.8.8 or leave empty for none): " whitelist_ips
+    IFS=',' read -r -a whitelistIPArray <<< "$whitelist_ips"
+
+    clear
+    if [[ $choice == 1 ]]; then
+        read -p "Enter the ports you want block for $isp (enter single like 443 or separated by comma like 443,8443): " ports
+        IFS=',' read -r -a portArray <<< "$ports"
+    fi
+
+    case $choice in
+        1)
+            clear
+            echo "Choose Protocol that you want to block for $isp"
+            echo "1-TCP & UDP"
+            echo "2-TCP"
+            echo "3-UDP"
+            read -p "Enter your choice: " protocol
+
+            case $protocol in
+            1) protocol="all" ;;
+            2) protocol="tcp" ;;
+            3) protocol="udp" ;;
+            *) echo "Invalid option"; blocker ;;
+            esac
+
+            clear
+            read -p "Do you want to delete the previous rules? [Y/N] : " confirm
+            if [[ $confirm == [Yy]* ]]; then
+                iptables -F isp-blocker
+                echo "Previous rules deleted successfully"
+                sleep 2s
+            fi
+
+            clear
+            echo "Blocking [$ports] for $isp started please wait..."
+
+            for ip in "${whitelistIPArray[@]}"; do
+                iptables -I isp-blocker -s $ip -j ACCEPT
+            done
+
+            for port in "${portArray[@]}"
+            do
+                for IP in $IP_LIST; do
+                    if [ "$protocol" == "all" ]; then
+                        iptables -A isp-blocker -s $IP -p tcp --dport $port -j DROP
+                        iptables -A isp-blocker -s $IP -p udp --dport $port -j DROP
+                    else
+                        iptables -A isp-blocker -s $IP -p $protocol --dport $port -j DROP
+                    fi
+                done
+            done
+
+            iptables-save > /etc/iptables/rules.v4
+
+            clear
+            if [ "$protocol" == "all" ]; then
+                echo "TCP & UDP [$ports] successfully blocked for $isp."
+            else
+                echo "$protocol [$ports] successfully blocked for $isp."
+            fi
+            ;;
+        2)
+            clear
+            read -p "Enter ports you want whitelist for $isp (separate with comma like 443,8443 or leave empty for none): " whitelist_ports
+            IFS=',' read -r -a whitelistPortArray <<< "$whitelist_ports"
+
+            clear
+            read -p "Enter the SSH port you want open for $isp (default is 22): " SSH_PORT
+            SSH_PORT=${SSH_PORT:-22}
+
+            clear
+            read -p "Do you want to delete the previous rules? [Y/N] : " confirm
+            if [[ $confirm == [Yy]* ]]; then
+                iptables -F isp-blocker
+                echo "Previous rules deleted successfully"
+                sleep 2s
+            fi
+
+            clear
+            echo "Blocking all ports for $isp started please wait..."
+
+            for ip in "${whitelistIPArray[@]}"; do
+                iptables -I isp-blocker -s $ip -j ACCEPT
+            done
+
+            for port in "${whitelistPortArray[@]}"; do
+                iptables -I isp-blocker -p tcp --dport $port -j ACCEPT
+                iptables -I isp-blocker -p udp --dport $port -j ACCEPT
+            done
+
+            if ! iptables -C isp-blocker -p tcp --dport "$SSH_PORT" -j ACCEPT 2>/dev/null; then
+                iptables -I isp-blocker -p tcp --dport "$SSH_PORT" -j ACCEPT
+            fi
+
+            for IP in $IP_LIST; do
+                iptables -A isp-blocker -s $IP -j DROP
+            done
+
+            iptables-save > /etc/iptables/rules.v4
+
+            clear
+            echo "All ports successfully blocked for $isp except for allowed ports."
+            ;;
+        3) main_menu ;;
+        *) echo "Invalid option"; blocker ;;
+    esac
+}
+
+function unblocker {
+    iptables -F isp-blocker
+    iptables-save > /etc/iptables/rules.v4
+    clear
+    echo "Unblock All IPs completed."
+    sleep 2s
+    main_menu
+}
+
+main_menu
